steps:
- name: "gcr.io/cloud-builders/docker"
args: ["build", "-t", "gcr.io/$PROJECT_ID/derivco:$_TAG",
       "--build-arg", "project_id=$PROJECT_ID", "."]
images: ["gcr.io/$PROJECT_ID/derivco:$_TAG"]
