version: '2'
services:
    api:
      build: .
      ports:
        - 4000
    proxy:
      image: 'dockercloud/haproxy:latest'
      links:
        - api
      ports:
        - 80:80
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock

